### ISSUE TITLE
[FEAT] Silencing collector console output

### ISSUE THREAD

**Issue by ShanDestromp** [AnalogJ/scrutiny#123]
Forgive me in advance if this is already available and I'm just a dunce and can't figure it out.

Right now, I have the collector running on bare metal via cron every 6 hours.  Everything works great, except it outputs the whole shebang.  My cron daemon is setup to email me any output from a task which results in my getting the collectors output every 6 hours in my email.

The traditional  `2>&1` doesn't accomplish anything and due to the regular messages it's resulted in my fighting against google as to whether or not it's spam.  This has resulted in my missing other messages from my cron daemon which *are* important.  Yes, I know I could setup filtering to auto-delete the messages caused by scrutiny but I would prefer not (as it would mean I would miss any actually *important* messages related to it's operation).

**Describe the solution you'd like**
A flag (ex `--quiet | -q`) that silences output on normal operation.  That is to say if there isn't a fundamental problem with *scrutiny* it should be quiet.  If it can't connect to the endpoint or some other error then sure, output to console so I'll get the email.

An alternative if complete silencing isn't possible/desired, would be altering the output to be more concise and human readable.  The message I get is **29,000** lines long (12 disks in my system).  A simple `/dev/sdX` is OK|Fault would work.

**Comment by AnalogJ** [comment]
Hey @ShanDestromp 

That's weird, `2>&1` should definitely work, since the collector is just logging to STDOUT by default. 
It should be possible to "silence" the logs by setting the log level to critical/error, but I'm unsure if that functionality is exposed via the config file/env variables. 

I can't make any promises about when this will get fixed, but thanks for submitting an issue, it's on my radar now 👍
