### ISSUE TITLE
[BUG] Unable to run collector in FreeBSD jail

### ISSUE THREAD

**Issue by claysam75** [AnalogJ/scrutiny#152]
**Describe the bug**
Following the manual install guide at docs/INSTALL_MANUAL.md. Installing in a TrueNAS jail - using Release 12.2 p4. 

Installed smartmontools successfully. Downloaded the latest linux-amd64 release from your github. 

Chmod successful. 

On trying to run, I get;

'ELF binary type "0" not known. ./scrutiny-collector-metrics-linux-amd64: Exec format error. Binary file not executable.'

**Expected behavior**
Single time run of the scrutiny collector

**Comment by ysguy** [comment]
Seems like you need to change ./scrutiny...... to the path where the collector is stored. i.e. /opt/scrutiny/bin/scrutiny......

**Comment by SxthGear** [comment]
I'm having the same issue and I don't believe it's based on where the file is stored. I think it's the fact it's a 64-bit linux image and FreeBSD doesn't support emulation for the executable. Not sure why FreeBSD wasn't supported right off the bat, but it looks like the author might add support for TrueNAS/FreeNAS/FreeBSD in the future based on #19 although it looks like development has been stale since last year. Other option might be to download the source yourself and compile your own binary.

**Comment by FingerlessGlov3s** [comment]
In the 0.3.1 release there's a FreeBSD build.

https://github.com/AnalogJ/scrutiny/releases/tag/0.3.1

**Comment by SxthGear** [comment]
@FingerlessGlov3s that did the trick. I wonder why FreeBSD builds weren't made after 0.3.1.

**Comment by FingerlessGlov3s** [comment]
I'm not sure either, I think it may of been added for testing, I found a PR/Issue about it a week ago, but I don't think they ever confirmed it stable (people testing didn't get back), but I've been using it for little while without any issues.

I'm hoping once AnalogJ is back working on the project he'll add it back to the build routine, so next release will include it once again.

**Comment by AnalogJ** [comment]
Hi,
Scrutiny releases will now include a FreeBSD version of the webserver and collector. 

If you have a moment, I'd appreciate it if you could test out the binaries and report back:

https://github.com/AnalogJ/scrutiny/releases/tag/0.3.10

Thanks!

**Comment by AnalogJ** [comment]
Closed with verification.
