### ISSUE TITLE
[Feature Request] scrutiny should show the RAW value column but currently does not

### ISSUE THREAD

**Issue by wallacebrf** [AnalogJ/scrutiny#186]
https://imgur.com/a/NyJZa5J

the collector is clearly saving the RAW values into the .db file, but the web portal is not showing the column. 

please add the ability to see this column

**Comment by mjmaisey** [comment]
Would be great to have this.

Currently the "Total LBAs Written" (ID 241) attribute - which is useful to assess SSD lifetime - only has useful information in the RAW_VALUE on some of my drives. On my Kingston SUV400S37120G I know from manual calcs vs the datasheet that I'm halfway through the specified TBW, but the VALUE is still 100. 

Because the metadata for ATA attribute ID indicates the display_type is normalised, the RAW_VALUE is never displayed. This trusts drives to do the right thing, and I suspect very many don't...

**Comment by AnalogJ** [comment]
please see the following comment in [275](https://github.com/AnalogJ/scrutiny/issues/275#issuecomment-1151976105) for a potential UI change that would solve your issue:

https://github.com/AnalogJ/scrutiny/issues/275#issuecomment-1151976105
