### ISSUE TITLE
[FEAT] Disk names/custom labels

### ISSUE THREAD

**Issue by sereeds** [AnalogJ/scrutiny#192]
I would like support for disk names.
You could add an "name" option like this for the collector config:

devices:
  - device: /dev/disk/by-uuid/1751e8d5-f09e-4961-9946-c2d84e1a313c
    type: 'ata'
    name: "Disk7"

So when I look at the web interface, it can show the name instead of disk path.
Similar to the host id name, but for disks also.

Thank you.

**Comment by AnalogJ** [comment]
Great idea, thanks

**Comment by ril3y** [comment]
Not sure this is the right place but it would be nice to be able to pass drives like this in docker:
- "/dev/disk/by-uuid/6cbbca25-c577-416a-a521-1379df4992cc" as systems with lots of drives dont always get the same name assigned to them.  UUID"s much more reliable.

**Comment by AnalogJ** [comment]
Hey @ril3y 
Thanks for resurfacing this issue for me. This was actually fixed in a previous version of Scrutiny:

- while `/dev/sd[abcdef]` device names are mutable, Scrutiny uses `WWN` identifiers internally, so your device history doesn't change
	- https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#wwn-vs-device-name
- Scrutiny now supports displaying disks using UUID, OS labels, and custom labels (as defined in the collector.yaml config file). 

I'm going to close this issue, but please feel free to comment/reopen if you have any further questions.
