### ISSUE TITLE
[FEAT] Show node id on temperature graph tooltip

### ISSUE THREAD

**Issue by FingerlessGlov3s** [AnalogJ/scrutiny#216]
**Is your feature request related to a problem? Please describe.**
When looking at the temperature graph at the bottom of the homepage. When you mouse over a data point to view its temperature there's no way to tell which `/dev/sda` drive it is.

This is only an issue when you multiple nodes all with their own `/dev/sda` drive.

**Describe the solution you'd like**
An extra line of text on the tooltip to display node id if available.

**Additional context**
No way to know which disk this is.
![image](https://user-images.githubusercontent.com/3495647/156894789-b745fec4-6d23-456c-a70d-c285977402f0.png)

**Comment by AnalogJ** [comment]
This should be partially fixed by #22, since the amount of data visible in the UI will be much more reasonable. 
However, as you noticed, this will still be an issue for multi-node deployments. 

We could add the node label as a prefix to the drive name. Another alternative would be to use the WWN identifier/UUID instead of disk name. Any preference?

**Comment by FingerlessGlov3s** [comment]
WWN is probably preferred, as this should be unique.

**Comment by AnalogJ** [comment]
fixed in `v0.4.7` 🎉
