### ISSUE TITLE
[FEAT] Show UUID in details page

### ISSUE THREAD

**Issue by fdw** [AnalogJ/scrutiny#265]
**Is your feature request related to a problem? Please describe.**
As a human, the traditional names (like `/dev/sda`) make more sense. But in my `fstab`, I use UUID. It would be nice if Scrutiny could show both at the same time. Or maybe even show the mountpoint of a device?

**Describe the solution you'd like**
I'd like to show both names and UUIDs for a device. Or, as a larger request, also the mount point.

**Comment by AnalogJ** [comment]
Hm, I think the Dashboard UI might get a bit cluttered with the addition of UUID information. 

What if I added the device UUID information to the details page? Would that be enough?

**Comment by fdw** [comment]
Sure, as long as it's somewhere 🙂

Do you think it's also possible to show where (or if) the device is currently mounted?

**Comment by AnalogJ** [comment]
I spent a long time researching that previously and unfortunately it doesn't look like it. 
Linux lets you mount your disk basically anywhere, and potentially to multiple locations at the same time. 

Also when the collector is running in a container, it's access to the host machine is limited (by design) so mounts there are not visible/accessible. 

No matter how much I'd like to, I don't think its a feature I'll be able to implement :(

**Comment by fdw** [comment]
Pity, that would have been cool. But thanks for trying, it's a nice tool 🙂
