### ISSUE TITLE
[FEAT] Write host id to InfluxDB

### ISSUE THREAD

**Issue by Panzer1119** [AnalogJ/scrutiny#313]
**Is your feature request related to a problem? Please describe.**
Currently the InfluxDB only has `device_protocol` and `device_wwn` as additional tags.

**Describe the solution you'd like**
For a Hub/Spoke deployment, with the host id set in `collector.yaml`, i would like to have the host id as an additional tag in the InfluxDB e.g. `device_host` or better just `host` (e.g. Telegraf also uses this name).

**Additional context**
Small Mockup in the InfluxDB Web interface:
![image](https://user-images.githubusercontent.com/23016343/175815437-b88f9a53-7bb4-4e80-80a7-a28da27fb476.png)

**Comment by AnalogJ** [comment]
I can definitely do that, but I'm curious why you need it? Are you using the InfluxDB web UI to graph something that Scrutiny doesn't provide?

**Comment by Panzer1119** [comment]
> I can definitely do that, but I'm curious why you need it? Are you using the InfluxDB web UI to graph something that Scrutiny doesn't provide? 
> 
> 

Yeah definitely, if I wanna display some data (e.g. temperature) in Grafana i need to be able to filter it by hosts.

Also it's not about whether or not Scrutiny can provide these graphs, but properly storing the complete Data.

So I can have graphs etc. from different sources and systems all in one place.

**Comment by AnalogJ** [comment]
to be frank, I'd almost rather you didn't do that. Scrutiny is under active development, and as I add additional data collectors I can't guarantee that the InfluxDB and sqlite schemas won't change significantly -- its an internal implementation detail. 

On the other hand, I've made an active effort to keep the API backwards compatible. Pulling data from there might be a safer idea. I'd be happy to expose more granular query functionality/endpoints if that's something that might work for you. 

Also, I've had requests in the past for providing ingest & export endpoints for Prometheus/Graphana/etc 
- #11 
- #74 

Would something like that be of interest?

**Comment by Panzer1119** [comment]
> to be frank, I'd almost rather you didn't do that. Scrutiny is under active development, and as I add additional data collectors I can't guarantee that the InfluxDB and sqlite schemas won't change significantly -- its an internal implementation detail. 

Do you mean you want to collect more that just SMART data?

If so, then Scrutiny would become more like Telegraf (a data collecting agent) and Telegraf also adds the hostname to the data, because that information is part of the data.



> On the other hand, I've made an active effort to keep the API backwards compatible. Pulling data from there might be a safer idea. I'd be happy to expose more granular query functionality/endpoints if that's something that might work for you. 

But then why are you using InfluxDB at all?



> Also, I've had requests in the past for providing ingest & export endpoints for Prometheus/Graphana/etc 

Do you mean that you want to display more data in Scrutiny from other sources or that Grafana etc can directly connect to Scrutiny?

If it's the second, than that would kinda be too much for just the hostname?

**Comment by AnalogJ** [comment]
> Do you mean you want to collect more that just SMART data?
> If so, then Scrutiny would become more like Telegraf (a data collecting agent) and Telegraf also adds the hostname to the data, because that information is part of the data.

Yep, I do plan on adding other data collectors ([disk utilization metrics](#35), [SMART long/short test results](#12), [etc.](#13)) 

> But then why are you using InfluxDB at all?

Not sure what you mean by this. InfluxDB is the persistent storage mechanism for Scrutiny. It's valuable because its designed for timeseries data and handles downsampling almost out of the box. While it **can** be directly accessed by users (because it's your data, at the end of the day), the intention is that scrutiny has full control over the schema (which can change between releases). 

On the other hand, the API is the intended mechanism for users to query and pull data for use in other systems. Fields like ["host_id", "device_status" and a bunch of others](https://github.com/AnalogJ/scrutiny/blob/master/webapp/backend/pkg/models/device.go#L21-L46) are only available in the SQLite DB. The API will merge the data from both sqlite and influxdb when you query it. Checkout `/api/summary` & `/api/summary/temp`

> Do you mean that you want to display more data in Scrutiny from other sources or that Grafana etc can directly connect to Scrutiny?

Mostly just a mechanism to export data from scrutiny, not an importer. There are lots of users who run their own monitoring/logging/tracing tools like ELK/Prometheus. The idea is to provide a way to export the SMART historical data that scrutiny contains, and make it available in a format that ELK/Prometheus can ingest. 

---

Sorry for the wall of text, and hopefully that all makes sense. If I added the host_id as a tagged field to influxdb, you'd probably notice that [there's a bunch of other fields that are also important that you're missing](https://github.com/AnalogJ/scrutiny/blob/master/webapp/backend/pkg/models/device.go#L21-L46) (since they're all stored in Sqlite still).

I'm going to close this issue for now, but happy to discuss further.

**Comment by Enissay** [comment]
@AnalogJ I am planning to deploy the collector on a few personal servers I have. How to know which one is concerned by an issue if I have no hostname ? I will then have to check them all one by one :-/

Unless I overlooked something ?

![image](https://user-images.githubusercontent.com/794673/206888408-79654d7e-7e4d-4ade-92b6-0c6352ebe9cb.png)

**Comment by AnalogJ** [comment]
Hey @Enissay that's already possible, just set a value for the `host.id` key in your collector config file (or `COLLECTOR_HOST_ID` environmental variable).

https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L21-L22

**Comment by Enissay** [comment]
I see, so basically i need to provide a `tag` ?! and that file should be provided for each machine manually!

The variable can help but it will be something other than the `hostname` at least in my swarm environment (I'll need some more tests)...

It feels more natural to always include the `hostname` on which the collector is running together with the generated metrics ?

**Comment by AnalogJ** [comment]
the host `hostname` is difficult to retrieve automatically when running in a docker container -- mostly because docker is designed to be isolated. If you have some ideas for how I can retrieve it consistently, I'm happy to investigate. 

But yes, you'll need to set a unique `host.id` value on each host:
- using the config file
- or env variable `COLLECTOR_HOST_ID`

I can see how that would be complicated in a Docker Swarm environment. 
However, it looks like you may be able to do some templating in the Swarm docker-compose file - https://stackoverflow.com/questions/50239470/node-hostname-usage-in-docker-compose-yml-in-docker-swarm-mode

**Comment by Enissay** [comment]
@AnalogJ Thank you very much for the support. That was indeed what I was testing, but I have introduced errors which were a nightmare to troubleshoot on some machine. Not to mention the DNS issue I had as well so everything was failing for no reason :x

Long story short, it finally works. I will leave it here for others.

```
COLLECTOR_HOST_ID: "{{.Node.Hostname}}"
```

**Comment by AnalogJ** [comment]
@Enissay If you'd be willing to write up a "How to Install on Docker Swarm" doc & open a PR, I'd be happy to add it to https://github.com/AnalogJ/scrutiny/tree/master/docs and link it in the Readme.
