### ISSUE TITLE
[FEAT] Add the possibility to run and submit metrics immediately/with delay after collector startup

### ISSUE THREAD

**Issue by Enissay** [AnalogJ/scrutiny#412]
**Is your feature request related to a problem? Please describe.**
When you deploy the collector, you have no feedback that it really works besides the lonely message `starting cron`.
You can play with the cron schedule to test it faster then change it back which is quite some useless work.
You can also access the container and run it manually `scrutiny-collector-metrics run` which is also useless extra work.

**Describe the solution you'd like**
It would be better if the collector runs once immediately at deployment to provide an immediate feedback

Well, maybe run it after a certain delay 20-30s since in swarm mode, the `depends_on` is not supported so if it starts immediately it might be unable to reach the end point which is still starting up).

`ENV_VAR` can be used as well to enable the first run as well as fix the delay duration (in seconds).

**Additional context**
-/-

**Comment by AnalogJ** [comment]
Great idea. Implemented via 2 env variables - `COLLECTOR_RUN_STARTUP` and `COLLECTOR_RUN_STARTUP_SLEEP`.

Please note, this only applies to the `collector` docker image.

**Comment by p0358** [comment]
@AnalogJ Why not default true? It's a bit confusing since the option is hardly documented (only mentioned in troubleshooting docs), plus in #95 this was enabled by default.

I propose either changing it to true by default, or at least adjusting default docker-compose example files to both include `COLLECTOR_RUN_STARTUP=false` in their environment section, so that users see this exists and can easily adjust it to true when setting it up.

**Comment by AnalogJ** [comment]
@p0358 good callout. I just updated the example docker-compose file with the env variable and a link to the troubleshooting docs.
