### ISSUE TITLE
[FEAT] Please produce arm64 binaries

### ISSUE THREAD

**Issue by lukehoersten** [AnalogJ/scrutiny#62]
I would like to use this on Raspberry Pi 4s with arm64 support.

**Comment by AnalogJ** [comment]
I have a issue tracking this work already. I'll have to check if Github Actions can run on an ARM OS. Though, it might just be as simple as doing a cross-compilation with Go. 

Dupe of #61  closing.

**Comment by lukehoersten** [comment]
I searched before posting! Must have been a race condition ;) Anyway thanks!

**Comment by AnalogJ** [comment]
Hey @lukehoersten  I just added Arm(32/64) builds to the CI.

If you're interested in testing it out, you can download the binaries.zip file from the CI here: [AnalogJ/scrutiny/actions/runs/285389324](https://github.com/AnalogJ/scrutiny/actions/runs/285389324)
You'll need to extract the file, `chmod +x scrutiny-collector-metrics-linux-arm`, and then run it via the [manual install instructions](https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md)

If you could [respond to this issue](https://github.com/AnalogJ/scrutiny/issues/61) with the results of your testing (either success & failure), that would fantastic, since this is a brand new binary.

**Comment by cameronetchart** [comment]
Hi @AnalogJ, thanks a bunch for adding arm/arm64 support. Unfortunately, I think Docker Hub is not building these versions under the latest tag or any other tag that I can find. Docker Hub says latest was updated 8 hours ago as of now, but the code was merged 3 days ago? 

Apologies if I'm missing something and just need to wait (I haven't made my own docker program before).

**Comment by AnalogJ** [comment]
@cameronetchart I actually don't know how to have Docker Hub create architecture variant images automatically. The work I did added binaries for arm/arm64, which can be used via the manual install instructions.

If you can point me to a link for how to build ARM images on Docker Hub, I'm happy to do so. My quick googling didn't come up with anything relevant.

**Comment by cameronetchart** [comment]
@AnalogJ  I believe they're called multi-arch images/builds, referenced by docker [here](https://docs.docker.com/docker-for-mac/multi-arch/) and [here](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/). Looks like Docker may have added native support for this within the last year; here's a [recent tutorial](https://medium.com/@admantium/docker-building-images-for-multiple-architectures-4f142f6dda71) I found.

I'll give the manual install a try for now too. Thanks!
