### ISSUE TITLE
Does Scrutiny run short/long tests?

### ISSUE THREAD

**Issue by ghnp5** [AnalogJ/scrutiny#639]
I understand there is a `COLLECTOR_CRON_SCHEDULE` that I can configure (defaults to once a day).

What does that cron do exactly?  
Is this to run the long tests?

So far, I had been running a self-coded cron that runs `smartctl --test=short <disk>` and `smartctl --test=long <disk>` periodically, for each disk.

Am I correct to say that I can safely disable `smartd` on the host, and no longer run these manual tests, and "rely" on Scrutiny to run the tests for me?  
Or is Scrutiny purely a web interface, and the tests are still to be triggered by me, and `smartd` should also be running on the host?

Thank you!

**Comment by MadWalnut** [comment]
@AnalogJ I have the same question. Thanks!

**Comment by kapsh** [comment]
It doesn't run any tests. `smartctl -t ...` nowhere to be seen in the code and no test records on my devices since last externally scheduled self-test. 
In theory, disk firmware should update some "important" age and pre-fail attributes on the fly and Scrutiny only fetchs new values and current temperature. But everybody feels safer running regular tests that, also in theory, should check disk's surface and mechanics better. Keep that cron.

Source: most interesting collector parts to read into
[scan for devices](https://github.com/AnalogJ/scrutiny/blob/master/collector/pkg/detect/detect.go#L30)
[get current metrics for each device](https://github.com/AnalogJ/scrutiny/blob/master/collector/pkg/collector/metrics.go#L117)
[default smartctl commands](https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L80)

**Comment by ghnp5** [comment]
Thank you!

Yeah, that's what I ended up figuring out.

Not a problem - the cron will continue running, so! 👍🏻👍🏻
