### ISSUE TITLE
[FEAT] Display Custom User Defined Fields for each Drive

### ISSUE THREAD

**Issue by curiousstyles** [AnalogJ/scrutiny#71]
I wish there was a way for the user to enter and display custom information about each drive on the Home screen.

I use it on unRAID with about 16 HDDs. Just noting the drive as "**dev/sdb - HGST HDN724040ALE640**" is not informative enough.

The option to see custom fields displayed on home screen would be very helpful. Something like this Photo-shopped image:

![Untitled-1](https://user-images.githubusercontent.com/56490391/94677664-4e59a500-02eb-11eb-8bb3-3641fd815f33.jpg)

Please consider implementing something like this.

Thank you.

H.

**Comment by hernandito** [comment]
This would be a nice feature. +1

**Comment by AnalogJ** [comment]
Yeah, custom drive labels are a good idea. I also need to provide an optional way to display (& filter) host machine labels/id. 

related #50

**Comment by AnalogJ** [comment]
this may be partially fixed in `v0.4.7`. I introduced multiple disk display title types:

- serial id
- wwn
- uuid
- scrutiny name
- device label

You can choose which one you'd like to use, and it makes it much easier to determine which drive is having issues. 
<img width="585" alt="Screen Shot 2022-05-23 at 9 11 31 AM" src="https://user-images.githubusercontent.com/891875/170308153-6481b8a8-82ca-4cd6-bc88-8a808bc36410.png">

**Comment by AnalogJ** [comment]
in the meantime, I'm going to close this issue, and track this work in #192 

Thanks!
