### ISSUE TITLE
[FEAT] Migrate Database Structure As Needed

### ISSUE THREAD

**Issue by dklinkman** [AnalogJ/scrutiny#83]
**Is your feature request related to a problem? Please describe.**
Not a problem really, but when a scrutiny docker container is recreated the collected smart drive information and presumably history metrics are lost.  I worked around this by creating a persistent volume for /scrutiny/config.

**Describe the solution you'd like**
Will the structure of scrutiny.db remain constant over time and future versions of scrutiny?  Or is the structure likely to evolve with the tool, meaning a persisted database may not work with a future version?  Depending on the answers a feature request might be an ability to [automagically] migrate the database to a new version, if necessary, when a container is recreated with a newer version of scrutiny.

**Comment by shamoon** [comment]
Yea +1 this, watchtower update last night and my stats were all wiped...

**Comment by AnalogJ** [comment]
Yeah, a volume/bind mount is required to persist the container data between restarts. 

Initially I didn't include it in the README docker command because I was constantly making breaking changes to the DB schema, but it's pretty stable now. DB schema automigration is already enabled in the ORM I'm using, though it's not as robust as I'd like.

**Comment by joe-eklund** [comment]
Ah I was looking for how to get my database to persist. I am currently mounting the `scrutiny/config` folder to a local disk, so that it will persist between container restarts. That way I can keep my history. Seems to be working fine.

Would you say this is acceptable for now? Or are there database breaking changes coming you think? @AnalogJ 

Another question, have you thought about using another docker image as the database (like mariadb/postgres)?

**Comment by AnalogJ** [comment]
Yeah thats probably the best way to do this for now @joe-eklund, eventually I'll probably have to move to InfluxDB, but I'll make sure there's a built in migration tool for existing data.

**Comment by AnalogJ** [comment]
Adding support for an external database is definitely on my to-do list. I use an ORM for structured data, which can be configured for multiple database types.
