### ISSUE TITLE
[FEAT] Upgrading

### ISSUE THREAD

**Issue by warwickchapman** [AnalogJ/scrutiny#86]
**Is your feature request related to a problem? Please describe.**

I need a way to see the current version installed and whether there is an update available and then know what steps to follow to upgrade.

**Describe the solution you'd like**

Please improve the documentation with steps to upgrade, including in hub/spoke case.

**Additional context**

I am happy to take rough instructions from here and commit a change to the documentation for merging but it may be easier just to update the docs and let us know.

Also, I did search before posting to see if I could find anything about updating or upgrading.

**Comment by AnalogJ** [comment]
Hey @warwickchapman 
For upgrading Scrutiny running via docker, you'll need to ensure a volume mount is configured for the db (`/scrutiny/config`, then you can just update the docker container image using something like Watchtower. 


For a manual install, you just need to download the new binaries from the release and replace the existing ones on your system.

Since it's a static installation, there's not much more than that required. Is there anything else you'd like to know?
